# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/walker/Workspace/paper/src/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/walker/Workspace/paper/src/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/walker/Workspace/paper/src/engine/CMakeFiles /home/walker/Workspace/paper/src/engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/walker/Workspace/paper/src/engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyidsd

# Build rule for target.
tinyidsd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyidsd
.PHONY : tinyidsd

# fast build rule for target.
tinyidsd/fast:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/build
.PHONY : tinyidsd/fast

ids_addr.o: ids_addr.cpp.o

.PHONY : ids_addr.o

# target to build an object file
ids_addr.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_addr.cpp.o
.PHONY : ids_addr.cpp.o

ids_addr.i: ids_addr.cpp.i

.PHONY : ids_addr.i

# target to preprocess a source file
ids_addr.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_addr.cpp.i
.PHONY : ids_addr.cpp.i

ids_addr.s: ids_addr.cpp.s

.PHONY : ids_addr.s

# target to generate assembly for a file
ids_addr.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_addr.cpp.s
.PHONY : ids_addr.cpp.s

ids_clinet.o: ids_clinet.cpp.o

.PHONY : ids_clinet.o

# target to build an object file
ids_clinet.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_clinet.cpp.o
.PHONY : ids_clinet.cpp.o

ids_clinet.i: ids_clinet.cpp.i

.PHONY : ids_clinet.i

# target to preprocess a source file
ids_clinet.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_clinet.cpp.i
.PHONY : ids_clinet.cpp.i

ids_clinet.s: ids_clinet.cpp.s

.PHONY : ids_clinet.s

# target to generate assembly for a file
ids_clinet.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_clinet.cpp.s
.PHONY : ids_clinet.cpp.s

ids_db.o: ids_db.cpp.o

.PHONY : ids_db.o

# target to build an object file
ids_db.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_db.cpp.o
.PHONY : ids_db.cpp.o

ids_db.i: ids_db.cpp.i

.PHONY : ids_db.i

# target to preprocess a source file
ids_db.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_db.cpp.i
.PHONY : ids_db.cpp.i

ids_db.s: ids_db.cpp.s

.PHONY : ids_db.s

# target to generate assembly for a file
ids_db.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_db.cpp.s
.PHONY : ids_db.cpp.s

ids_db_adapter.o: ids_db_adapter.cpp.o

.PHONY : ids_db_adapter.o

# target to build an object file
ids_db_adapter.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_db_adapter.cpp.o
.PHONY : ids_db_adapter.cpp.o

ids_db_adapter.i: ids_db_adapter.cpp.i

.PHONY : ids_db_adapter.i

# target to preprocess a source file
ids_db_adapter.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_db_adapter.cpp.i
.PHONY : ids_db_adapter.cpp.i

ids_db_adapter.s: ids_db_adapter.cpp.s

.PHONY : ids_db_adapter.s

# target to generate assembly for a file
ids_db_adapter.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_db_adapter.cpp.s
.PHONY : ids_db_adapter.cpp.s

ids_epoll.o: ids_epoll.cpp.o

.PHONY : ids_epoll.o

# target to build an object file
ids_epoll.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_epoll.cpp.o
.PHONY : ids_epoll.cpp.o

ids_epoll.i: ids_epoll.cpp.i

.PHONY : ids_epoll.i

# target to preprocess a source file
ids_epoll.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_epoll.cpp.i
.PHONY : ids_epoll.cpp.i

ids_epoll.s: ids_epoll.cpp.s

.PHONY : ids_epoll.s

# target to generate assembly for a file
ids_epoll.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_epoll.cpp.s
.PHONY : ids_epoll.cpp.s

ids_http.o: ids_http.cpp.o

.PHONY : ids_http.o

# target to build an object file
ids_http.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_http.cpp.o
.PHONY : ids_http.cpp.o

ids_http.i: ids_http.cpp.i

.PHONY : ids_http.i

# target to preprocess a source file
ids_http.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_http.cpp.i
.PHONY : ids_http.cpp.i

ids_http.s: ids_http.cpp.s

.PHONY : ids_http.s

# target to generate assembly for a file
ids_http.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_http.cpp.s
.PHONY : ids_http.cpp.s

ids_log.o: ids_log.cpp.o

.PHONY : ids_log.o

# target to build an object file
ids_log.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_log.cpp.o
.PHONY : ids_log.cpp.o

ids_log.i: ids_log.cpp.i

.PHONY : ids_log.i

# target to preprocess a source file
ids_log.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_log.cpp.i
.PHONY : ids_log.cpp.i

ids_log.s: ids_log.cpp.s

.PHONY : ids_log.s

# target to generate assembly for a file
ids_log.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_log.cpp.s
.PHONY : ids_log.cpp.s

ids_string_util.o: ids_string_util.cpp.o

.PHONY : ids_string_util.o

# target to build an object file
ids_string_util.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_string_util.cpp.o
.PHONY : ids_string_util.cpp.o

ids_string_util.i: ids_string_util.cpp.i

.PHONY : ids_string_util.i

# target to preprocess a source file
ids_string_util.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_string_util.cpp.i
.PHONY : ids_string_util.cpp.i

ids_string_util.s: ids_string_util.cpp.s

.PHONY : ids_string_util.s

# target to generate assembly for a file
ids_string_util.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_string_util.cpp.s
.PHONY : ids_string_util.cpp.s

ids_tcpflow.o: ids_tcpflow.cpp.o

.PHONY : ids_tcpflow.o

# target to build an object file
ids_tcpflow.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_tcpflow.cpp.o
.PHONY : ids_tcpflow.cpp.o

ids_tcpflow.i: ids_tcpflow.cpp.i

.PHONY : ids_tcpflow.i

# target to preprocess a source file
ids_tcpflow.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_tcpflow.cpp.i
.PHONY : ids_tcpflow.cpp.i

ids_tcpflow.s: ids_tcpflow.cpp.s

.PHONY : ids_tcpflow.s

# target to generate assembly for a file
ids_tcpflow.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/ids_tcpflow.cpp.s
.PHONY : ids_tcpflow.cpp.s

md5.o: md5.cpp.o

.PHONY : md5.o

# target to build an object file
md5.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/md5.cpp.o
.PHONY : md5.cpp.o

md5.i: md5.cpp.i

.PHONY : md5.i

# target to preprocess a source file
md5.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/md5.cpp.i
.PHONY : md5.cpp.i

md5.s: md5.cpp.s

.PHONY : md5.s

# target to generate assembly for a file
md5.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/md5.cpp.s
.PHONY : md5.cpp.s

tinyids.o: tinyids.cpp.o

.PHONY : tinyids.o

# target to build an object file
tinyids.cpp.o:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/tinyids.cpp.o
.PHONY : tinyids.cpp.o

tinyids.i: tinyids.cpp.i

.PHONY : tinyids.i

# target to preprocess a source file
tinyids.cpp.i:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/tinyids.cpp.i
.PHONY : tinyids.cpp.i

tinyids.s: tinyids.cpp.s

.PHONY : tinyids.s

# target to generate assembly for a file
tinyids.cpp.s:
	$(MAKE) -f CMakeFiles/tinyidsd.dir/build.make CMakeFiles/tinyidsd.dir/tinyids.cpp.s
.PHONY : tinyids.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tinyidsd"
	@echo "... ids_addr.o"
	@echo "... ids_addr.i"
	@echo "... ids_addr.s"
	@echo "... ids_clinet.o"
	@echo "... ids_clinet.i"
	@echo "... ids_clinet.s"
	@echo "... ids_db.o"
	@echo "... ids_db.i"
	@echo "... ids_db.s"
	@echo "... ids_db_adapter.o"
	@echo "... ids_db_adapter.i"
	@echo "... ids_db_adapter.s"
	@echo "... ids_epoll.o"
	@echo "... ids_epoll.i"
	@echo "... ids_epoll.s"
	@echo "... ids_http.o"
	@echo "... ids_http.i"
	@echo "... ids_http.s"
	@echo "... ids_log.o"
	@echo "... ids_log.i"
	@echo "... ids_log.s"
	@echo "... ids_string_util.o"
	@echo "... ids_string_util.i"
	@echo "... ids_string_util.s"
	@echo "... ids_tcpflow.o"
	@echo "... ids_tcpflow.i"
	@echo "... ids_tcpflow.s"
	@echo "... md5.o"
	@echo "... md5.i"
	@echo "... md5.s"
	@echo "... tinyids.o"
	@echo "... tinyids.i"
	@echo "... tinyids.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

